# Site settings
title: Adobe Web Platform Team
description: "The Adobe Web Platform Team mission is to create a more expressive web. Here, we give a broad view into our different projects. Some projects will make their way into browsers, web standards, open source projects, and Adobe tools."
baseurl: ""
url: "http://webplatform.adobe.com"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [design]
